In [26]:
import six
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from pylab import *
from sklearn.model_selection import train_test_split
import tensorflow as tf
from sklearn import preprocessing
import os
import six.moves.urllib.request as request
import tensorflow as tf
from sklearn.metrics import classification_report
# Check that we have correct TensorFlow version installed
tf_version = tf.__version__
print("TensorFlow version: {}".format(tf_version))
assert "1.4" <= tf_version, "TensorFlow r1.4 or later is needed"
from datetime import datetime

TensorFlow version: 1.7.0

In [547]:
#original  = pd.read_csv('https://raw.githubusercontent.com/essebrowns/RadProject/master/survey_imputed2.csv', skiprows=0,delimiter=',')
#original.head()

,Music,Slow.songs.or.fast.songs,Dance,Folk,Country,Classical.music,Musical,Pop,Rock,Metal.or.Hardrock,...,Age,Height,Weight,Number.of.siblings,Gender,Left...right.handed,Education,Only.child,Village...town,House...block.of.flats
0,5,3,2,1,2,2,1,5,5,1,...,20,163,48,1,1,0,4,0,1,0
1,4,4,2,1,1,1,2,3,5,4,...,19,163,58,2,1,0,4,0,0,0
2,5,5,2,2,3,4,5,3,5,3,...,20,176,67,2,1,0,3,0,0,0
3,5,3,2,1,1,1,1,2,2,1,...,22,172,59,1,1,0,4,1,0,1
4,5,3,4,3,2,4,3,5,3,1,...,20,170,59,1,1,0,3,0,1,1

In [72]:
#original = pd.read_csv("final_survey_norm.csv", skiprows=0, delimiter=',')
#original.head(10)

,Music,Slow.songs.or.fast.songs,Dance,Folk,Country,Classical.music,Musical,Pop,Rock,Metal.or.Hardrock,...,Parents..advice,Questionnaires.or.polls,Internet.usage,Finances,Shopping.centres,Branded.clothing,Entertainment.spending,Spending.on.looks,Spending.on.gadgets,Spending.on.healthy.eating
0,1.0,0.5,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,1.0,0.5,0.5,0.5,1.0,1.0,0.5,0.5,0.0,0.5
1,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.5,1.0,1.0,...,0.0,0.5,0.5,0.5,1.0,0.0,1.0,0.0,1.0,0.0
2,1.0,1.0,0.0,0.0,0.5,1.0,1.0,0.5,1.0,0.5,...,0.5,0.0,0.5,0.0,1.0,0.0,1.0,0.5,1.0,0.0
3,1.0,0.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,1.0,0.5,0.5,1.0,1.0,0.0
4,1.0,0.5,1.0,0.5,0.0,1.0,0.5,1.0,0.5,0.0,...,0.5,0.5,0.5,1.0,0.5,1.0,0.5,0.5,0.0,1.0
5,1.0,0.5,0.0,0.5,0.0,0.5,0.5,0.0,1.0,1.0,...,0.5,1.0,0.5,0.0,0.5,0.5,0.5,0.0,1.0,1.0
6,1.0,1.0,1.0,0.5,0.0,0.0,0.0,1.0,0.5,0.0,...,1.0,1.0,0.0,1.0,0.5,0.0,0.5,1.0,0.0,1.0
7,1.0,0.5,0.5,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0.5,0.5,0.5,0.5,1.0,1.0,1.0,1.0,0.5,0.0
8,1.0,0.5,0.5,0.0,0.0,0.0,1.0,0.5,1.0,1.0,...,1.0,0.5,0.5,0.0,0.0,0.5,0.0,0.0,0.5,1.0
9,1.0,0.5,0.0,1.0,0.0,0.0,1.0,0.5,1.0,0.0,...,0.5,0.5,0.5,1.0,1.0,1.0,0.0,0.5,0.0,1.0

In [175]:
original = pd.read_csv('survey_simple.csv', skiprows=0,delimiter=',')
#original.head()

In [176]:
original = original.replace([-1, 0, 1], [1,2,3])
#original.iloc[:,71]
original.head()

,Music,Slow.songs.or.fast.songs,Dance,Folk,Country,Classical.music,Musical,Pop,Rock,Metal.or.Hardrock,...,Parents..advice,Questionnaires.or.polls,Internet.usage,Finances,Shopping.centres,Branded.clothing,Entertainment.spending,Spending.on.looks,Spending.on.gadgets,Spending.on.healthy.eating
0,3,2,1,1,1,1,1,3,3,1,...,3,2,2,2,3,3,2,2,1,2
1,3,3,1,1,1,1,1,2,3,3,...,1,2,2,2,3,1,3,1,3,1
2,3,3,1,1,2,3,3,2,3,2,...,2,1,2,1,3,1,3,2,3,1
3,3,2,1,1,1,1,1,1,1,1,...,1,3,3,1,3,2,2,3,3,1
4,3,2,3,2,1,3,2,3,2,1,...,2,2,2,3,2,3,2,2,1,3

In [177]:
#original.replace([-1, 0, 1], [0,0.5,1])

In [362]:
#Isolates x and y given k = the target. Normalizes x and then splits train/test
df=original
#k=71 # Doggs
#k = 68 # Snakes
k = 72 # Public Speaking
#k = 67 #spiders
colname = df.columns[k]
xdf = df.drop(colname, axis = 1)
min_max_scaler = preprocessing.MinMaxScaler()
xdf1 = min_max_scaler.fit_transform(xdf)
xdf = pd.DataFrame(xdf1, columns=xdf.columns)
ydf = df.iloc[:,k]
'''
for i in range(0,len(ydf)-1):
    if ydf[i]>0:
        ydf[i]=1
    #elif ydf[i]==0:
    #    ydf[i]=2
    else:
        ydf[i]=0
'''
x_train, x_test, y_train, y_test = train_test_split(xdf,ydf,test_size=0.3,random_state=151)

In [363]:
print(ydf.head())

0    1
1    3
2    1
3    3
4    2
Name: Fear.of.public.speaking, dtype: int64

In [180]:
#print(df.shape)
#df = test

In [291]:
'''
##Music
#Isolates x and y given k = the target. Normalizes x and then splits train/test
df=original
for i in range(18,140):
    df.drop(df.columns[18], axis=1, inplace=True)
df.drop(df.columns[0], axis=1, inplace=True)
k=71
colname = df.columns[k]
xdf = df.drop(colname, axis = 1)
min_max_scaler = preprocessing.MinMaxScaler()
xdf1 = min_max_scaler.fit_transform(xdf)
xdf = pd.DataFrame(xdf1, columns=xdf.columns)
ydf = df.iloc[:,k]
for i in range(0,len(ydf)-1):
    if ydf[i]>0:
        ydf[i]=1
    #elif ydf[i]==0:
    #    ydf[i]=2
    else:
        ydf[i]=0
x_train, x_test, y_train, y_test = train_test_split(xdf,ydf,test_size=0.3,random_state=151)
'''

'\n##Music\n#Isolates x and y given k = the target. Normalizes x and then splits train/test\ndf=original\nfor i in range(18,140):\n    df.drop(df.columns[18], axis=1, inplace=True)\ndf.drop(df.columns[0], axis=1, inplace=True)\nk=71\ncolname = df.columns[k]\nxdf = df.drop(colname, axis = 1)\nmin_max_scaler = preprocessing.MinMaxScaler()\nxdf1 = min_max_scaler.fit_transform(xdf)\nxdf = pd.DataFrame(xdf1, columns=xdf.columns)\nydf = df.iloc[:,k]\nfor i in range(0,len(ydf)-1):\n    if ydf[i]>0:\n        ydf[i]=1\n    #elif ydf[i]==0:\n    #    ydf[i]=2\n    else:\n        ydf[i]=0\nx_train, x_test, y_train, y_test = train_test_split(xdf,ydf,test_size=0.3,random_state=151)\n'

In [ ]:
#for i in range(0,len(ydf)-1):
#    if ydf[i]<0:
#        ydf[i]=1
#    elif ydf[i]==0:
#        ydf[i]=2
#    else:
#        ydf[i]=3

In [688]:
#####Don't use
#Normalizing the x sets
#min_max_scaler = preprocessing.MinMaxScaler()
#xtr_scaled = min_max_scaler.fit_transform(x_train)
#x_train = pd.DataFrame(xtr_scaled, columns=x_train.columns)
##min_max_scaler = preprocessing.MinMaxScaler()
#xte_scaled = min_max_scaler.fit_transform(x_test)
#x_test = pd.DataFrame(xte_scaled, columns=x_test.columns)
#min_max_scaler = preprocessing.MinMaxScaler()

In [381]:
print(x_test.head())
print(y_test.head())

In [182]:
#Don't use yet. Will work on later. This creates onehot y

#label_binarizer = preprocessing.LabelBinarizer()
#label_binarizer.fit(range(max(y_train)))
#y_train = label_binarizer.transform(y_train)
#label_binarizer = preprocessing.LabelBinarizer()
#label_binarizer.fit(range(max(y_test)))
#y_test = label_binarizer.transform(y_test)

In [364]:
##Creates list of features to pipe into estimator
features = x_train.columns
tf_variables =[]
for index in features:
    tf_variables.append(tf.feature_column.numeric_column(str(index)))

In [376]:
tf_variables

In [366]:
print(x_train.shape) 
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(707, 139)
(303, 139)
(707,)
(303,)

In [367]:
##pandas
input_func=tf.estimator.inputs.pandas_input_fn(x=x_train,y=y_train,batch_size=100,num_epochs=None,shuffle=False)

In [377]:
model = tf.estimator.DNNClassifier(feature_columns=tf_variables, hidden_units=[1024,512,256,128],optimizer=tf.train.ProximalAdagradOptimizer(
      learning_rate=0.01),dropout=.1,n_classes=303,activation_fn=tf.nn.relu)

IndentationError: unexpected indent (<ipython-input-377-d0506df8beeb>, line 2)

In [378]:
start_time = datetime.now()
model.train(input_fn = input_func, steps=30000)
end_time = datetime.now()
print("Duration: {}".format(end_time - start_time))

Duration: 0:00:00.000076

In [371]:
#pandas
pred_fn = tf.estimator.inputs.pandas_input_fn(x=x_test,batch_size=len(x_test),shuffle=False)

In [372]:
predictions = list(model.predict(input_fn=pred_fn))

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpn_6lmaoj/model.ckpt-30001
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.

In [373]:
final_preds = []
for pred in predictions:
    final_preds.append(pred['class_ids'][0])

In [379]:
#final_preds[:10]
#final_preds

In [380]:
print(classification_report(y_test,final_preds))

K = 71 # Dangerous Dogs
         Prec      Recall    f1-score  support  steps
relu >>  0.48      0.50      0.48       303     2000
relu >>  0.50      0.50      0.50       303     10000
relu >>  0.50      0.50      0.50       303     30000
relu >>  0.48      0.49      0.48       303     50000

K = 68 # Snakes
         Prec      Recall    f1-score  support  steps
relu >>   0.62      0.63      0.63       303    2000
relu >>   0.58      0.61      0.60       303    10000
relu >>   0.61      0.63      0.62       303    30000
relu >>   0.62      0.64      0.63       303    50000

K = 72 # Public Speaking
         Prec      Recall    f1-score  support  steps
relu >>  0.52      0.51      0.51       303     2000
relu >>  0.51      0.50      0.50       303     30000
relu >>  0.51      0.50      0.50       303     10000
relu >>  0.50      0.49      0.49       303     50000

K = 67 # Spiders
         Prec      Recall    f1-score  support  steps
relu >>  0.57      0.58      0.57       303     2000
relu >>  0.57      0.59      0.57       303     10000
relu >>  0.56      0.58      0.56       303     30000
relu >>  0.56      0.59      0.57       303     50000